### ISSUE TITLE
MetricsRegistryImpl.register is not thread-safe

### ISSUE THREAD

**Issue by stiefel40k** [smallrye/smallrye-metrics#112]

**Comment by jmartisk** [comment]
Hi, thanks for the report, yes we are aware that it is not entirely thread-safe and I will try and see what can be done without introducing unnecessarily too much synchronization, slowing the performance. If you have any particular use case example (a reproducer) where the thread-unsafeness causes an issue it would be welcome and I would add a test for that particular use case.
