### ISSUE TITLE
metric registration log spam

### ISSUE THREAD

**Issue by Ladicek** [smallrye/smallrye-metrics#123]
I often see a lot of log messages about metric registration, such as

> ```
> Kvě 20, 2019 6:15:58 ODP. io.smallrye.metrics.MetricsRegistryImpl get
> INFO: Register metric [metricId: MetricID{name='ft.org.eclipse.microprofile.fault.tolerance.tck.fallback.clientserver.FallbackOnlyClient.serviceB.fallback.calls.total', tags=[]}, type: counter]
> ```

I consider them log spam. Is the `INFO` level intentional? I'd personally say it should be `DEBUG`.

**Comment by pilhuhn** [comment]
I think it is at the end a leftover from the very first implementation that I did, where those made a lot of sense. 
I am not opposed to tune them down or even totally remove them.

**Comment by jmartisk** [comment]
Yes I've noticed this too and I would suggest demoting them to `DEBUG`. Will prepare a PR soon
