### ISSUE TITLE
smallrye-metrics-2.0-1.0.0 works with Wildfly 16.0.0 

### ISSUE THREAD

**Issue by rsoika** [smallrye/smallrye-metrics#128]
I just want to inform you that I build a custom docker image with Wildfly 16.0.0 and smallrye-metrics-2.0-1.0.0. This works great with MP-metrics 2.0 !

https://ralph.blog.imixs.com/2019/05/27/wildfly-16-0-0-with-microprofile-metrics-2-0-0/

**Comment by jmartisk** [comment]
Hey Ralph, that's absolutely awesome, thanks for letting us know :) I can't say for sure in which WildFly version this will be bundled out-of-the-box, but I will try to make sure it happens soon.
