### ISSUE TITLE
Metrics exporter should be more robust

### ISSUE THREAD

**Issue by jmesnil** [smallrye/smallrye-metrics#14]
Both JSON and Prometheus exporters iterate over the metrics without acknowledging that failures may occur when the value is fetched.
A single Metric that fails will result in a HTTP 500 error.

I think that in that case, that'd be better to remove the failing metric from the export (and log the error) so that other metrics can still be retrieved from the HTTP endpoint.

**Comment by kenfinnigan** [comment]
Fixed by #15
