### ISSUE TITLE
snake case conversion is not producing expected name

### ISSUE THREAD

**Issue by jmesnil** [smallrye/smallrye-metrics#16]
In the Prometheus exporter, the MP Metric name is converted to snake case to match Prometheus format.

However, while testing it, I found out that there were issues when the metric name was having succeeding upper case characters:

*  `FRAG3` became `f_ra_g3`
* `UNICAST3` became `u_ni_ca_st3`

The conversion should be fixed to output correct snake case names (in my case, `frag3` and `unicast3`).

**Comment by pilhuhn** [comment]
Fixed in #17
