### ISSUE TITLE
branch 2.1.x must be renamed to 2.0.x

### ISSUE THREAD

**Issue by jmesnil** [smallrye/smallrye-metrics#162]
https://github.com/smallrye/smallrye-metrics/tree/2.1.x branch is used to build smallrye-metrics for MP Metrics 2.0.1 (according to its [pom.xml](https://github.com/smallrye/smallrye-metrics/blob/2.1.x/pom.xml#L36))

The branch must be renamed 2.0.x to avoid any confusion.

**Comment by jmartisk** [comment]
The thing with implementing MP Metrics 2.0.1 is correct, after recently reverting the versioning scheme change, SmallRye Metrics 2.1 implements MP Metrics 2.0.x and SmallRye Metrics 2.2 will implement MP Metrics 2.1.x, there are some commits missing right now though (the re-versioning), see https://github.com/smallrye/smallrye-metrics/pull/158#issuecomment-520719404 @kenfinnigan  should have the correct contents of the branch locally, I guess

**Comment by jmesnil** [comment]
oh, my mistake, I did not realise smallrye-metrics already reverted its versioning scheme.
