### ISSUE TITLE
Ordering of metrics in output

### ISSUE THREAD

**Issue by jmartisk** [smallrye/smallrye-metrics#170]
At the moment the ordering of metrics in JSON and OpenMetrics output is undefined and pretty random. While the spec doesn't mandate any ordering, we might want to think whether to include any (perhaps alphabetical) ordering. While the output is primarily used for machines, it would help humans with troubleshooting. We should also make sure that this doesn't come at too much of a performance penalty (or the user should be able to turn it off if it does).

**Comment by jmartisk** [comment]
This doesn't look like something we really need after all - unless the spec starts to require it (but I doubt that).
I'll close this for now

**Comment by jimbogithub** [comment]
Actually, sorting (grouping) is a requirement: https://prometheus.io/docs/instrumenting/exposition_formats/#grouping-and-sorting

It makes this current output from version 2.3.2 non-conformant:
```
# HELP application_streaming_sendCount_total Message send count.
# TYPE application_streaming_sendCount_total counter
application_streaming_sendCount_total{type="SystemNotification"} 8.0
application_streaming_sendCount_total{type="MarketSummary"} 289418.0
application_streaming_sendCount_total{type="TradeSummary"} 930.0
# HELP application_streaming_activeCount Current connection count.
# TYPE application_streaming_activeCount gauge
application_streaming_activeCount 3.0
application_streaming_sendCount_total{type="Candles"} 863.0
```

`application_streaming_sendCount_total{type="Candles"}` is misplaced and in our case not picked up by the monitoring tool (DataDog).

I haven't been able to test newer version as we are using Thorntail which is managing the version.

**Comment by jimbogithub** [comment]
From examining the source of newer jars, I suspect this problem still exists in 2.3.3 and 2.4.1 and therefore impacts Quarkus as well as Thorntail.

Is the quick fix to change `io.smallrye.metrics.MetricsRegistryImpl` to use a `ConcurrentSkipListMap` ?
```
    // Only this map needs to be concurrent because it is being iterated in getMetrics which is not synchronized.
    // Other maps are accessed only in synchronized methods.
    private Map<MetricID, Metric> metricMap = new ConcurrentHashMap<>();
```

**Comment by jmartisk** [comment]
Hey @jimbogithub, how I understand your comment is that the problem is that lines connected to the same metric aren't grouped together, right? This issue was meant about something different - about alphabetically ordering the lines, which I think is not required by Prometheus nor DataDog (correct me if I'm wrong on the latter).

According to your output it seems that lines pertaining to one metric are indeed not grouped together, which is definitely wrong. I will get that fixed asap.

**Comment by jmartisk** [comment]
I wanted to do this (keep lines pertaining to one metric together) without necessarily also sorting the metrics alphabetically, but it turns out that due to the somewhat clumsy design, it would need quite a big refactoring of the exporter for that, so for now let's actually sort the metrics alphabetically. If it turns out to be too much of a performance issue, I'll do the refactoring.

**Comment by Ladicek** [comment]
I'd like to have this fixed in Thorntail 2.7, which will support MicroProfile 3.3 (that is, MP Metrics 2.3). I don't know which SmallRye Metrics version implements MP Metrics 2.3, but if this was fixed in that branch, that would be nice :-)

**Comment by jmartisk** [comment]
Ok it will be backported to SR-M 2.4.x (MP Metrics 2.3): https://github.com/smallrye/smallrye-metrics/pull/307 :)

**Comment by Ladicek** [comment]
Thanks!

**Comment by jimbogithub** [comment]
@jmartisk Your assessment of the issue is correct.  I'll take the Thorntail 2.7 when it's available.

Thanks to all for the prompt resolution.
