### ISSUE TITLE
Collapse TCK modules into one, or rename

### ISSUE THREAD

**Issue by kenfinnigan** [smallrye/smallrye-metrics#2]
Not sure if there's a particular reason for `/testsuite/api` and `testsuite/rest` being separate as their all part of TCK testing.

If it's necessary for them to be separate, I would suggest renaming to `/api-tck` and `/rest-tck`.

Otherwise I would collapse them both into a single `/testsuite/tck`

**Comment by michalszynkiewicz** [comment]
@kenfinnigan, `api` tests can run with arquillian-weld-embedded whereas the `rest` tests require wildfly arquillian container which is much slower. Besides, the TCK itself is split into two.
I wouldn't say it's necessary to have them separate but it looked clearer to me.

**Comment by kenfinnigan** [comment]
It's fine them being separate, but maybe renaming to what I'd suggested to make it clearer what is TCK tests and what are additional

**Comment by michalszynkiewicz** [comment]
Okay, will do. 
BTW, do you have a better name for the additional tests module? Right now it's called `extra`.

**Comment by kenfinnigan** [comment]
anything like that or `additional` works.
