### ISSUE TITLE
Hacks needed to support Micrometer compatibility mode

### ISSUE THREAD

**Issue by jmartisk** [smallrye/smallrye-metrics#234]
- Option to skip prepending the scope in OpenMetrics export for particular metrics (implemented as a `ExtendedMetadata` attribute)
- Option to override the name mapping in OpenMetrics export (Micrometer has different rules, for example we might want to skip adding the `_total` suffix for counters)
- ???

**Comment by jmesnil** [comment]
@jmartisk 

> * Option to skip prepending the scope in OpenMetrics export for particular metrics (implemented as a `ExtendedMetadata` attribute)

Isn't that already covered by https://github.com/smallrye/smallrye-metrics/blob/ecf5188bb1532e82c6d7b12301e15c5aa307f00c/implementation/src/main/java/io/smallrye/metrics/ExtendedMetadata.java#L43?

**Comment by jmartisk** [comment]
@jmesnil Well, that option appends it as a tag, we want to skip the scope completely :(
