### ISSUE TITLE
Performance cost of new MetricID

### ISSUE THREAD

**Issue by loicmathieu** [smallrye/smallrye-metrics#247]
The performance cost of `new MetricID` is high as it uses `Config config = ConfigProvider.getConfig();` that has a non negligeable performance cost.

The `MetricID` is used first to register a metric, then to recover a metric from the registry from the CDI interceptors.

I wonder if there will be a way, inside the CDI interceptors, to cache the `MetricID` instead of re-creating them each time. It will avoid the cost of creating the `MetricID`.

I discover it when profiling a Quarkus application but I think it is not related to Quarkus so I openned an issue here.

**Comment by jmartisk** [comment]
Well this is not even SmallRye code, this is in MP Metrics API. And I agree that it is sub-optimal, also from the PoV that the API code is basically performing something that the implementation itself should do, which generally happens somewhat more than would be appropriate. We have an issue open for that more general problem of the spec (https://github.com/eclipse/microprofile-metrics/issues/506), I added a comment that we should specifically open up ways for implementation to supply the necessary metric tags itself, so they can potentially be cached.
I'll close this issue now, you can follow the MP Metrics issue if interested. Thanks!

**Comment by loicmathieu** [comment]
As I said, on smallrye part, it's possible to cache the MetricID inside the various interceptors instead of re-creating them on each call. This will be easily feasible via a simple Map based cache.

But if you think that it's better to have a solution on the spec level, OK for me.

**Comment by jmartisk** [comment]
Well, I think you can't work around the fact that the constructor contains that call (always), and that constructor is not in your codebase. Not if you want to stay compliant with the specification. IMO this indeed needs a solution on the spec level.

**Comment by loicmathieu** [comment]
If you cache the `MetricID` and retrieve them by name inside the interceptor, you will create them once insead of for each call.
But if the spec didn't allow such implementation, well, yes, it is something that needs to be done at the spec level.
