### ISSUE TITLE
Provide a FunctionTimer

### ISSUE THREAD

**Issue by svenhaag** [smallrye/smallrye-metrics#257]
Hi, please can we have this one too?

https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-core/src/main/java/io/micrometer/core/instrument/FunctionTimer.java

**Comment by jmartisk** [comment]
Hi, I'm not super familiar with Micrometer, but from looking at that class, it looks very much like the new `SimpleTimer` facility introduced in MP Metrics 2.3 - it measures the count of invocations, and the total time spent. See https://download.eclipse.org/microprofile/microprofile-metrics-2.3/microprofile-metrics-spec-2.3.html#_simplytimed
It is implemented in SmallRye Metrics 2.4.0 that was just released. Does that suffice for your use case?

**Comment by svenhaag** [comment]
Hi, the description indeed looks like so, but the implementation only seems to measure the time?

[SimplyTimedInterceptor#94](https://github.com/smallrye/smallrye-metrics/blob/2.4.0/implementation/src/main/java/io/smallrye/metrics/interceptors/SimplyTimedInterceptor.java#L94)

The FunctionTimer on the other hand counts all events **and** the total time spent. See the measurement: 
https://github.com/micrometer-metrics/micrometer/blob/v1.3.5/micrometer-core/src/main/java/io/micrometer/core/instrument/FunctionTimer.java#L65

**Comment by jmartisk** [comment]
It measures the count as well, the `SimpleTimer.Context.stop()` method calls `SimpleTimerImpl.update()` which then increments both the elapsed time and the count: https://github.com/smallrye/smallrye-metrics/blob/2.4.0/implementation/src/main/java/io/smallrye/metrics/app/SimpleTimerImpl.java#L132

**Comment by svenhaag** [comment]
Awesome, thanks
