### ISSUE TITLE
Metadata Equality Check to Restrictive

### ISSUE THREAD

**Issue by svenhaag** [smallrye/smallrye-metrics#258]
Hi,

when registering a metric it is checked if another metric with the same name (org.eclipse.microprofile.metrics.MetricID#name) exists. If so, it is verified that both MetaData are equal. Any Tag differences, which are also part of a [metrics ID](https://download.eclipse.org/microprofile/microprofile-metrics-2.3/microprofile-metrics-spec-2.3.html#metricid-data-def), are ignored, see:
[MetricsRegistryImpl.java#L121](https://github.com/smallrye/smallrye-metrics/blob/2.4.0/implementation/src/main/java/io/smallrye/metrics/MetricsRegistryImpl.java#L121)

So this config:
```
buffer.memory.total.displayName: BufferPool Total Capacity
buffer.memory.total.type: gauge
buffer.memory.total.unit: bytes
buffer.memory.total.multi: true
buffer.memory.total.mbean: java.nio:type=BufferPool,name=%s/TotalCapacity
buffer.memory.total.description: The memory used by the NIO pool: %s
buffer.memory.total.tags: name=%s1
```
creates 2 metrics with the name `buffer.memory.total`, but the Tags are different.

1. buffer.memory.total(name=mapped)
1. buffer.memory.total(name=direct)

**Unfortunately this is an invalid config because the descriptions are different!**

Furthermore, the logged exception is not very helpful with finding the problem:

```
java.lang.IllegalStateException: Description differs from previous usage
        at io.smallrye.metrics.MetricsRegistryImpl.verifyMetadataEquality(MetricsRegistryImpl.java:197)
        at io.smallrye.metrics.MetricsRegistryImpl.register(MetricsRegistryImpl.java:149)
        at io.smallrye.metrics.setup.JmxRegistrar.register(JmxRegistrar.java:74)
        ...
```
It would be great to see the metrics name at least.

**Comment by jmartisk** [comment]
This behavior is correct per spec, it is possible to have multiple metrics with the same name and different tags, but then all the metadata have to be equal (for each metric that has a particular name). That in this case effectively means that the metric description cannot contain wildcards.

To improve the exception we could potentially employ some more strict checks on the contents of `base-metrics.properties` and `vendor-metrics.properties`, but these files aren't meant to be something that application developers use (only frameworks should use them) so I generally thought it's not quite necessary. But if you want to improve that, PRs are welcome :) 

Not quite sure how to exactly do that check though - we could detect that there is a wildcard in the description of a metric that has `multi=true`, but that still does not absolutely guarantee that it will blow up during registration.

**Comment by jmartisk** [comment]
Hey @svenhaag , as I explained why this is correct behavior, I'll close this issue now, if you have any more concerns about it or would like to implement some more checking for the `base/vendor.properties` files (I'm not quite sure if it's actually worth it), let me know
