### ISSUE TITLE
Create some documentation

### ISSUE THREAD

**Issue by jmartisk** [smallrye/smallrye-metrics#267]
I think it's about time we make some documentation to
- describe how to integrate SmallRye Metrics in various runtimes
- what are the things we add on top of the spec (specifically `ExtendedMetadata`)
etc

**Comment by kenfinnigan** [comment]
Also keep https://github.com/smallrye/smallrye-parent/issues/68 in mind as we want to have the same approach for all projects, so that we can have docs.smallrye.io, or the like, with them all there

**Comment by jmartisk** [comment]
Cool, thanks, will do that the same way.

**Comment by kenfinnigan** [comment]
Well, we don't have that defined yet, hence the issue on high level planning.

If as part of this you want to look at how it can all integrate, you're more than welcome to

**Comment by jmartisk** [comment]
Oh, I was referring to your comment about how reactive messaging does it https://github.com/smallrye/smallrye-parent/issues/68#issuecomment-575800709

**Comment by kenfinnigan** [comment]
Ah, yeah I'm not sure if that's going to be "the way" or not

**Comment by jmartisk** [comment]
There is a basic version live now, so I'll close this
