### ISSUE TITLE
quarkus-smallrye-metrics "application_" instead of "application: "

### ISSUE THREAD

**Issue by bartekkocik** [smallrye/smallrye-metrics#347]
Hi, For some time I have been wondering why the metrics from quarkus app are not getting to prometheus and grafana. I have found that the metrics returned by the qarkus have a different form than those from thorntail for example:
Quarkus 1.7.1.Final
with

            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-smallrye-metrics</artifactId>

which use microprofile-metrics-api 2.3 and impl smallrye-metrics-2.4.2

return application metrics in form
"application_some_metric_example"

in case of thorntail 2.4.0.Final

            <groupId>io.thorntail</groupId>
            <artifactId>microprofile-metrics</artifactId>

which use microprofile-metrics-api-1.1 with impl smallrye-metrics 1.1.3

have form like:
"application:some_metric_example"
Is there a compatible model? Can I force a change in the base prefix format?

**Comment by jmartisk** [comment]
Hi @bartekkocik, this is something that changed in the MP Metrics spec between 1.x and 2.x, and it's not the only change in the output format.  We don't provide a compatibility switch. I'm afraid you'll need to refresh your Grafana dashboard. If I may suggest, look at https://github.com/jamesfalkner/microprofile-grafana which is a tool that knows how to generate a Grafana dashboard, if you let it look into the output of a running MP Metrics deployment

**Comment by bartekkocik** [comment]
Hi, thanks for answer. 
I have verified versions and this Prometheus accept both formats.
This is my misconfiguration I forgot to add 

```
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
```

to my deployment definition (template part).
