### ISSUE TITLE
WeightedSnapshot blocking vert.x event loop for 60s 

### ISSUE THREAD

**Issue by dfa1** [smallrye/smallrye-metrics#423]
Hello,

 I'm using quarkus 1.4.2 with smallrye-metrics 2.2 on OpenJDK 11. This morning I got this error in openshift (just before the POD restart):

```
{
  "loggerName":"io.vertx.core.impl.BlockedThreadChecker",
  "level":"WARNING",
  "logMessage":"Thread Thread[vert.x-worker-thread-16,5,main]=Thread[vert.x-worker-thread-16,5,main] has been blocked for 60275 ms, time limit is 60000 ms",
  "threadName":"vertx-blocked-thread-checker",
  "threadId":19,
  "processId":1,
  "exception":{"refId":1,"exceptionType":"io.vertx.core.VertxException","message":"Thread blocked","frames":[{"class":"java.util.Comparator","method":"lambda$comparing$77a9974f$1","line":469},{"class":"java.util.Comparator$$Lambda$135/0x00000008001ca040","method":"compare"},{"class":"java.util.TimSort","method":"binarySort","line":296},{"class":"java.util.TimSort","method":"sort","line":239},{"class":"java.util.Arrays","method":"sort","line":1441},{"class":"io.smallrye.metrics.app.WeightedSnapshot","method":"<init>","line":64},{"class":"io.smallrye.metrics.app.ExponentiallyDecayingReservoir","method":"getSnapshot","line":162},{"class":"io.smallrye.metrics.app.HistogramImpl","method":"getSnapshot","line":90},{"class":"io.smallrye.metrics.exporters.OpenMetricsExporter","method":"writeHistogramValues","line":289},{"class":"io.smallrye.metrics.exporters.OpenMetricsExporter","method":"exposeEntries","line":224},{"class":"io.smallrye.metrics.exporters.OpenMetricsExporter","method":"getEntriesForScope","line":158},{"class":"io.smallrye.metrics.exporters.OpenMetricsExporter","method":"exportAllScopes","line":109},{"class":"io.smallrye.metrics.MetricsRequestHandler","method":"handleRequest","line":116},{"class":"io.smallrye.metrics.MetricsRequestHandler_ClientProxy","method":"handleRequest","line":239},{"class":"io.quarkus.smallrye.metrics.runtime.SmallRyeMetricsHandler","method":"handle","line":35},{"class":"io.quarkus.smallrye.metrics.runtime.SmallRyeMetricsHandler","method":"handle","line":17},{"class":"io.vertx.ext.web.impl.BlockingHandlerDecorator","method":"lambda$handle$0","line":48},{"class":"io.vertx.ext.web.impl.BlockingHandlerDecorator$$Lambda$454/0x000000080076ac40","method":"handle"},{"class":"io.vertx.core.impl.ContextImpl","method":"lambda$executeBlocking$2","line":316},{"class":"io.vertx.core.impl.ContextImpl$$Lambda$456/0x000000080076d040","method":"run"},{"class":"io.vertx.core.impl.TaskQueue","method":"run","line":76},{"class":"io.vertx.core.impl.TaskQueue$$Lambda$281/0x000000080060b440","method":"run"},{"class":"java.util.concurrent.ThreadPoolExecutor","method":"runWorker","line":1128},{"class":"java.util.concurrent.ThreadPoolExecutor$Worker","method":"run","line":628},{"class":"io.netty.util.concurrent.FastThreadLocalRunnable","method":"run","line":30}, 
```

It looks like there are two problems:
- we are sorting a huge array (there is a way to keep a maximum number of entries?)
- sorting is happening in the event loop (there is a way to use a worker thread?)

Any advice/comment will be appreciated (I know that this is an old version and the new version has a different design...)

**Comment by jmartisk** [comment]
The processing does happen in the worker thread, in your snippet it says `vert.x-worker-thread-16`, so it looks like the problem is just that building the histogram snapshot is taking too long.

Which comes at a surprise to me, because the value reservoirs for histograms, unless you override that behavior, have a capacity of 1028 - see https://github.com/smallrye/smallrye-metrics/blob/3.0.3/implementation/src/main/java/io/smallrye/metrics/app/ExponentiallyDecayingReservoir.java#L56

I can't imagine how a reservoir of 1028 values could take longer than a minute to process (including sorting the 1028 values). 
Could it be that the `/metrics` endpoint is scraped extremely often? Other explanation coming to my mind is that the sizing is not properly handled and more values are let into the reservoir.
If it helps, it should be possible to reduce the size from 1028, but I suppose it should not be necessary under normal circumstances.

**Comment by dfa1** [comment]
thanks for your reply! I'm still investigating on my side with grafana and splunk (maybe the JVM was not healthy).

Just a question: the  constant 1028 was already there in version 2.2.0?

**Comment by jmartisk** [comment]
Yes, that hasn't changed basically since the beginning, when SmallRye Metrics was extracted out of Thorntail into a separate project.

**Comment by dfa1** [comment]
Over the night we have additional problems like this one. And there some strong correlation with OOMs... so I'm going to close this ticket.

Thank you @jmartisk for your support!
