### ISSUE TITLE
No error information provided if 'requestPath' does not start with 'contextRoot'

### ISSUE THREAD

**Issue by the-bug** [smallrye/smallrye-metrics#428]
Hello,
first at all: I am not sure if this is an issue of smallrye metrics or undertow.
Currently I am integrating smallrye metrics(2.4.6) into an app based on undertow.

I am using the function handleRequest (https://github.com/smallrye/smallrye-metrics/blob/2.4.6/implementation/src/main/java/io/smallrye/metrics/MetricsRequestHandler.java#L75) in order to do so.
But I am using a different context root as in https://github.com/smallrye/smallrye-metrics/blob/2.4.6/implementation/src/main/java/io/smallrye/metrics/MetricsRequestHandler.java#L79 is set as default.
As expected I get a 500 if I try to call the metrics endpoint. (See: https://github.com/smallrye/smallrye-metrics/blob/2.4.6/implementation/src/main/java/io/smallrye/metrics/MetricsRequestHandler.java#L105)

But there is no logging information provided although https://github.com/smallrye/smallrye-metrics/blob/2.4.6/implementation/src/main/java/io/smallrye/metrics/MetricsRequestHandler.java#L105 f provides useful information.
The current logging just says:
`STDOUT: 2021-05-14 09:06:08 DEBUG XNIO-1 task-1 [i.u.r.error-response] Setting error code 500 for exchange HttpServerExchange{ GET /v1/metrics/application}java.lang.RuntimeException: null`

I would expect the log message contains the information described in https://github.com/smallrye/smallrye-metrics/blob/2.4.6/implementation/src/main/java/io/smallrye/metrics/MetricsRequestHandler.java#L105 f  and that the log level is at least WARN.

**Comment by jmartisk** [comment]
Hi @the-bug,
the log you're seeing looks like something specifically logged by Undertow (when there's a '500' response), SmallRye currently doesn't log anything, it just sends a response with the particular code and message.
I agree though that spewing something into the log would be a good idea, because this indicates a misconfiguration problem on the server side, not an invalid request from the client.
So, would adding a WARN log (along with setting the response) using a `org.jboss.logging.Logger` do it for you? I think that would be a good thing to do.

**Comment by the-bug** [comment]
Hi @jmartisk ,
thank you for the quick response!
If SmallRye does not log than this should not start with this ticket, I think. I am using logback.
I will open a ticket in the undertow project. Maybe i screwed something up in this part...
@jmartisk thx again

**Comment by jmartisk** [comment]
I don't think it's a problem of Undertow in any way. 
Undertow simply decided to make a log when there's a 500 response, appending info about the exception that caused that 500 response.
However, SmallRye simply sets the response code, without throwing any exception or so, so Undertow has no way to know what to include in the log.
If something is supposed to appear in the log, it has to be done by SmallRye.

**Comment by the-bug** [comment]
@jmartisk okay that sounds legit.
What would be a good way for logging? In my project we are working with slf4j and logback.
I just seen over the weekend that there are adapters for jboss logging but I am not an expert at this topic.

**Comment by jmartisk** [comment]
I submitted a PR for the fix: https://github.com/smallrye/smallrye-metrics/pull/429
Will this do it for you? It's for the 2.4.x branch, but 3.0.x would get something similar too

**Comment by jmartisk** [comment]
The log from Undertow will still appear too, but I that's not something SmallRye can control

**Comment by the-bug** [comment]
It looks good to me! Thank you!
I have added two minor comments. Feel free to ignore them!
I am currently using 2.4.6 so this is just fine for me.
@jmartisk thanks again!

**Comment by jmartisk** [comment]
Merged, it will be in 2.4.7. There are currently no other changes on top of 2.4.6, so no immediate plans for 2.4.7, therefore I suppose I'll have to release it just for you ;)

**Comment by the-bug** [comment]
My own release :D 
Thats something to boast :D

**Comment by jmartisk** [comment]
Ok, I just did the 2.4.7 release, it should appear in Maven Central repository within 2 hours at most
