### ISSUE TITLE
second TYPE line for metric

### ISSUE THREAD

**Issue by blxbrgld** [smallrye/smallrye-metrics#457]
The **_sum GAUGE** introduced by [this](https://github.com/smallrye/smallrye-metrics/commit/164ab9a235309f728aae7e7624bc0c9f797bca47) pull request, leads to the following Prometheus failure: `second TYPE line for metric name "application_api_request_seconds", or TYPE reported after samples`.

If I understand correctly, the new `_sum` value conflicts with the summary metric defined by OpenMetrics ([here](https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#summary-1)) and this raises a Prometheus error ([here](https://github.com/prometheus/common/blob/main/expfmt/text_parse.go#L511)) because of the duplicate metric name.

**Comment by jmartisk** [comment]
This will be fixed in SR Metrics 3.0.4 (I'll probably release it later this week)

**Comment by svenreimers** [comment]
> This will be fixed in SR Metrics 3.0.4 (I'll probably release it later this week)

Any chance of a timely release? The issue at hand stops us from getting any data into our observability system (after migrating to WildFly 25). Thanks for considering.

**Comment by jmartisk** [comment]
@svenreimers Argh, I completely forgot about that. My apologies. I'll release it today.

**Comment by jmartisk** [comment]
Here it is: https://repo1.maven.org/maven2/io/smallrye/smallrye-metrics/3.0.4/

**Comment by svenreimers** [comment]
Awesome. Thanks.
