### ISSUE TITLE
[metrics 5.0] automatically tag app metrics with application scope

### ISSUE THREAD

**Issue by donbourne** [smallrye/smallrye-metrics#503]
automatically add `scope=application` tag to application metrics being registered using the MP metrics API where the metric being registered does not already have a defined scope tag.

In cases where application metric being registered has a scope tag, verify that the value satisfies regex `[a-zA-Z_][a-zA-Z0-9_]*` (in cases where it doesn't, throw an IllegalArgumentException)

**Comment by Channyboy** [comment]
Related to https://github.com/smallrye/smallrye-metrics/issues/502
