### ISSUE TITLE
Missing message insert when custom scope not found

### ISSUE THREAD

**Issue by donbourne** [smallrye/smallrye-metrics#534]
When you use the `/metrics` endpoint with a scope that has no registered metrics, the browser returns:

http://localhost:9080/metrics?scope=x
```
Scope  not found
```

<img width="373" alt="image" src="https://user-images.githubusercontent.com/17110503/187738470-23178d96-5946-480f-b92f-ee5b7b20f55e.png">

**Comment by Channyboy** [comment]
Dup of #535
