### ISSUE TITLE
MetricsRegistryImpl.register(Metadata, T) ignores Metadata.tags

### ISSUE THREAD

**Issue by schulzp** [smallrye/smallrye-metrics#64]
Hi!

I'm using *smallrye-metrics* as part of wildfly 15 and noticed that I cannot have multiple instances of a metric (with the same name) distinguished only by tags. For example, with the original [prometheus implementation](https://github.com/prometheus/client_java/) allows for measuring load-times per page by means of a [servlet filter](https://github.com/prometheus/client_java/blob/master/simpleclient_servlet/src/main/java/io/prometheus/client/filter/MetricsFilter.java), which uses one and the same metric but with different tag values to distinguish between multiple URLs.

According to the spec for 1.1.1 [MetricsRegistry.register(Metadata, T)](https://github.com/eclipse/microprofile-metrics/blob/994058c23bcbdcb49e22926427cee0fb392ede1a/api/src/main/java/org/eclipse/microprofile/metrics/MetricRegistry.java#L153) is supposed to "register it under the provided Metadata". Wouldn't that include tags as well?

**Comment by jmartisk** [comment]
Hi, unfortunately no, in MicroProfile Metrics 1.1, only the `name` is used as a unique identifier of the metric, so there can only be one metric with a particular name. 
But we are well aware that this is very limiting and unintuitive, and it is going to change in specification 2.0 which should be out quite soon, where we introduce the notion of `MetricID` as a unique identifier for metrics, and that `MetricID` consists of a name and a set of tags, and it will be possible to register multiple metrics with the same name, but differentiated by tags.

I can't promise you exact dates, but the 2.0 spec should be out in a few weeks and the implementation of this in SmallRye Metrics 2.0 will then follow.

**Comment by schulzp** [comment]
Thanks a lot for your quick response, @jmartisk! Two weeks sounds promising, and I'm looking forward to that.
