### ISSUE TITLE
@Timed annotation for Async code

### ISSUE THREAD

**Issue by lordvlad** [smallrye/smallrye-metrics#678]
The @Timed annotation does not seem to work for async code as expected. Simple example

```
@Timed
public Uni<Void> doSomething() {
        Uni.createFrom().voidItem().onItem().delayIt().by(Duration.ofSeconds(10));
}
``` 

Will result sub-millisecond timings.

I have created a custom TimedInterceptor in our code which handles it properly, which I'd like to contribute. I didn't find a quick way to disable the default TimedInterceptor provided by smallrye, and now we have the timings recorded twice (one of them has an additional `async` tag.

Before contributing back I wanted to ask if the team would rather
1. have a separate, dedicated `@AsyncTimed` annotation with a dedicated Interceptor
2. or have the default interceptor check the return type of the returned method and act accordingly

Cheers

**Comment by Channyboy** [comment]
Hello, which release(s) of SmallRye would you plan on targeting?

**Comment by lordvlad** [comment]
I've since abandoned this effort. Quarkus will drop support for smallrye metrics and they have their own timed annotation which handles mutiny nicely
